---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
#  become_method: sudo
#  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  pre_tasks:
    - name: wait 120 seconds for target connection to become reachable/usable.
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 120
  roles:
    - configure-server
    - configure-prometheus-node-exporter