- name: "install node, npm and pm2"
  become: yes
  shell: |
    echo "---- dpkg --configure -a ----"
    sudo dpkg --configure -a
    echo "---- apt update ----"
    sudo apt update
    echo "---- apt upgrade ----"
    sudo apt upgrade
    echo "---- apt install -y python3-zunclient ----"
    sudo apt install -y python3-zunclient
    echo "---- apt install -y nodejs ----"
    sudo apt install -y nodejs
    echo "---- apt install -y npm ----"
    sudo apt install -y npm
    echo "---- npm install pm2@latest -g ----"
    sudo npm install pm2@latest -g
    echo "---- hostname: {{inventory_hostname}} ----"
    echo "---- env variables ----"
    export TYPEORM_CONNECTION=postgres 
    export TYPEORM_MIGRATIONS_DIR=./src/migrations 
    export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts 
    export TYPEORM_MIGRATIONS=./src/migrations/*.ts 
    export TYPEORM_HOST={{inventory_hostname}} 
    export TYPEORM_PORT=5432 
    export TYPEORM_USERNAME=postgres 
    export TYPEORM_PASSWORD=postgres 
    export TYPEORM_DATABASE=postgres
    env
#- name: "update apt packages."
#  become: yes
#  apt:
#    update_cache: yes
#
#- name: "upgrade packages"
#  become: yes
#  apt:
#    upgrade: yes
#
#- name: remove dependencies that are no longer required
#  become: yes
#  apt:
#    autoremove: yes
#
#- name: "install nodejs, npm."
#  become: yes
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
##    update_cache: yes
#
#- name: "install pm2"
#  become: yes
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: present