- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: install dependencies
  become: yes
  shell: |
    apt install python3.10
#    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
#    source ~/.bashrc
#    nvm --version
#    nvm install v16
#    npm install -g npm@8.14.0
#    npm install --global --production pm2
