- name: "copy file"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/
    backup: yes
- name: "extract file"
  become: yes
  shell: |
    tar -xvzf artifact.tar.gz 

- name: "run backend"
  become: yes
  shell: |
    ls
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start