- name: "copy file"
  copy:
    src: ~/artifact.tar.gz
    dest: ~/
    backup: yes
- name: "extract file"
  become: yes
  shell: |
    tar –xvzf artifact.tar.gz

- name: "run backend"
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start