#- name: "copy file"
#  copy:
#    src: ~/project/artifact.tar.gz
#    dest: ~/
#    backup: yes
#- name: "extract file"
#  become: yes
#  shell: |
#    tar -xvzf artifact.tar.gz
#
#- name: "run backend"
#  become: yes
#  shell: |
#    ls
#    npm install
#    npm run build
#    pm2 stop default
#    pm2 start npm -- start

#- name: "update and install"
#  become: yes
#  environment:
#    ENVIRONMENT: production
#    TYPEORM_CONNECTION: postgres
#    TYPEORM_MIGRATIONS_DIR: ./src/migrations
#    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
#    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
#    TYPEORM_HOST: 34.203.10.167
#    TYPEORM_PORT: 5432
#    TYPEORM_USERNAME: postgres
#    TYPEORM_PASSWORD: postgres
#    TYPEORM_DATABASE: postgres
#  shell: |
#    sudo apt update
#    sudo apt-get update && sudo apt-get -y upgrade
#    sudo apt install -y nodejs
#    sudo apt install -y npm
#    sudo npm install pm2@latest -g

#- name: "export to env"
#  become: yes
#  shell: |
#    export TYPEORM_CONNECTION=postgres
#    export TYPEORM_MIGRATIONS_DIR=./src/migrations
#    export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
#    export TYPEORM_MIGRATIONS=./src/migrations/*.ts
#    export TYPEORM_HOST=50.19.29.112
#    export TYPEORM_PORT=5432
#    export TYPEORM_USERNAME=postgres
#    export TYPEORM_PASSWORD=postgres
#    export TYPEORM_DATABASE=postgres

#- name: "set environment variables"
#  ansible.builtin.package:
#    name: cobbler
#    state: present
#  environment:
#    ENVIRONMENT: production
#    TYPEORM_CONNECTION: postgres
#    TYPEORM_MIGRATIONS_DIR: ./src/migrations
#    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
#    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
#    TYPEORM_HOST: 34.203.10.167
#    TYPEORM_PORT: 5432
#    TYPEORM_USERNAME: postgres
#    TYPEORM_PASSWORD: postgres
#    TYPEORM_DATABASE: postgres


- name: "run app"
  become: yes
  shell: |
    git clone https://github.com/ehabrefaat82/cdond-c3-projectstarter.git
    cd cdond-c3-projectstarter/backend
    npm install
    npm run build
    npm audit fix --audit-level=critical --force
    pm2 start npm -- start
  environment:
    ENVIRONMENT: production
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"