version: 2.1


jobs:
  build-frontend: # req 01-f
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: build frontend
          command: |
            pwd
            cd frontend
            npm install
            npm run build
  build-backend: # req 01-b
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: build backend
          command: |
            pwd
            cd backend
            npm install
            npm run build

# ------------------------
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend